# Generated by Django 3.2.12 on 2022-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='market_values',
            new_name='stock_market',
        ),
        migrations.RemoveField(
            model_name='company',
            name='symbol',
        ),
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(default='', max_length=10, verbose_name='Stocks ticker'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
